//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 11:51:40 PM IST 
//


package springapp.domain.NSS.NSSResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NssMapOffender complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NssMapOffender">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identity" type="{}NssOffenderIdentity"/>
 *         &lt;element name="aliasNames" type="{}NssAliasNames"/>
 *         &lt;element name="aliasDOBs" type="{}NssaliasDOBs"/>
 *         &lt;element name="record" type="{}NssOffendeRecord"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NssMapOffender", propOrder = {
    "identity",
    "aliasNames",
    "aliasDOBs",
    "record"
 })
public class NssMapOffender {

    @XmlElement(required = true)
    protected NssOffenderIdentity identity;
    @XmlElement(required = true)
    protected NssAliasNames aliasNames;
    @XmlElement(required = true)
    protected NssaliasDOBs aliasDOBs;
    @XmlElement(required = true)
    protected NssOffendeRecord record;
    
    

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link NssOffenderIdentity }
     *     
     */
    public NssOffenderIdentity getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link NssOffenderIdentity }
     *     
     */
    public void setIdentity(NssOffenderIdentity value) {
        this.identity = value;
    }

    /**
     * Gets the value of the aliasNames property.
     * 
     * @return
     *     possible object is
     *     {@link NssAliasNames }
     *     
     */
    public NssAliasNames getAliasNames() {
        return aliasNames;
    }

    /**
     * Sets the value of the aliasNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NssAliasNames }
     *     
     */
    public void setAliasNames(NssAliasNames value) {
        this.aliasNames = value;
    }

    /**
     * Gets the value of the aliasDOBs property.
     * 
     * @return
     *     possible object is
     *     {@link NssaliasDOBs }
     *     
     */
    public NssaliasDOBs getAliasDOBs() {
        return aliasDOBs;
    }

    /**
     * Sets the value of the aliasDOBs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NssaliasDOBs }
     *     
     */
    public void setAliasDOBs(NssaliasDOBs value) {
        this.aliasDOBs = value;
    }

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link NssOffendeRecord }
     *     
     */
    public NssOffendeRecord getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link NssOffendeRecord }
     *     
     */
    public void setRecord(NssOffendeRecord value) {
        this.record = value;
    }

	
    
    

}
