//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 11:51:40 PM IST 
//


package springapp.domain.NSS.NSSResponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NssOffenders complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NssOffenders">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offender" type="{}NssMapOffender" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NssOffenders", propOrder = {
    "offender"
})
public class NssOffenders {

    @XmlElement(required = true)
    protected List<NssMapOffender> offender;
    
    @XmlAttribute(name = "qtyFound")
    protected Integer qtyFound;
    @XmlAttribute(name = "qtyReturned")
    protected Integer qtyReturned;

    /**
     * Gets the value of the offender property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offender property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffender().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NssMapOffender }
     * 
     * 
     */
    
    
    public List<NssMapOffender> getOffender() {
        if (offender == null) {
            offender = new ArrayList<NssMapOffender>();
        }
        return this.offender;
    }

	public Integer getQtyFound() {
		return qtyFound;
	}

	public void setQtyFound(Integer qtyFound) {
		this.qtyFound = qtyFound;
	}

	public Integer getQtyReturned() {
		return qtyReturned;
	}

	public void setQtyReturned(Integer qtyReturned) {
		this.qtyReturned = qtyReturned;
	}

	

}
