//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 11:51:40 PM IST 
//


package springapp.domain.NSS.NSSResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NssOffenderHeight complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NssOffenderHeight">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="feet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inches" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NssOffenderHeight", propOrder = {
    "feet",
    "inches"
})
public class NssOffenderHeight {

    @XmlElement(required = true)
    protected String feet;
    @XmlElement(required = true)
    protected String inches;

    /**
     * Gets the value of the feet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeet() {
        return feet;
    }

    /**
     * Sets the value of the feet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeet(String value) {
        this.feet = value;
    }

    /**
     * Gets the value of the inches property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInches() {
        return inches;
    }

    /**
     * Sets the value of the inches property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInches(String value) {
        this.inches = value;
    }

}
