//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 11:51:40 PM IST 
//


package springapp.domain.NSS.NSSResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NSSProductMapHolder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NSSProductMapHolder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NationalSecurityOneSearch" type="{}NSOS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NSSProductMapHolder", propOrder = {
    "nationalSecurityOneSearch"
})
public class NSSProductMapHolder {

    @XmlElement(name = "NationalSecurityOneSearch", required = true)
    protected NSOS nationalSecurityOneSearch;
   

    /**
     * Gets the value of the nationalSecurityOneSearch property.
     * 
     * @return
     *     possible object is
     *     {@link NSOS }
     *     
     */
    public NSOS getNationalSecurityOneSearch() {
        return nationalSecurityOneSearch;
    }

    /**
     * Sets the value of the nationalSecurityOneSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link NSOS }
     *     
     */
    public void setNationalSecurityOneSearch(NSOS value) {
        this.nationalSecurityOneSearch = value;
    }

	
    

}
