//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.30 at 11:51:40 PM IST 
//


package springapp.domain.NSS.NSSResponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the NSSResponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BGC_QNAME = new QName("", "BGC");
    private final static QName _SecureKey_QNAME = new QName("", "secureKey");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: NSSResponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NSSMapHolder }
     * 
     */
    public NSSMapHolder createNSSMapHolder() {
        return new NSSMapHolder();
    }

    /**
     * Create an instance of {@link NSSSummary }
     * 
     */
    public NSSSummary createNSSSummary() {
        return new NSSSummary();
    }

    /**
     * Create an instance of {@link NssMapOffender }
     * 
     */
    public NssMapOffender createNssMapOffender() {
        return new NssMapOffender();
    }

    /**
     * Create an instance of {@link NssOffenders }
     * 
     */
    public NssOffenders createNssOffenders() {
        return new NssOffenders();
    }

    /**
     * Create an instance of {@link NssOffenderIdentity }
     * 
     */
    public NssOffenderIdentity createNssOffenderIdentity() {
        return new NssOffenderIdentity();
    }

    /**
     * Create an instance of {@link NSOS }
     * 
     */
    public NSOS createNSOS() {
        return new NSOS();
    }

    /**
     * Create an instance of {@link NssOffendeRecord }
     * 
     */
    public NssOffendeRecord createNssOffendeRecord() {
        return new NssOffendeRecord();
    }

    /**
     * Create an instance of {@link NssAliasNames }
     * 
     */
    public NssAliasNames createNssAliasNames() {
        return new NssAliasNames();
    }

    /**
     * Create an instance of {@link NssaliasDOBs }
     * 
     */
    public NssaliasDOBs createNssaliasDOBs() {
        return new NssaliasDOBs();
    }

    /**
     * Create an instance of {@link NssOffenderPersonal }
     * 
     */
    public NssOffenderPersonal createNssOffenderPersonal() {
        return new NssOffenderPersonal();
    }

    /**
     * Create an instance of {@link NSSResponse }
     * 
     */
    public NSSResponse createNSSResponse() {
        return new NSSResponse();
    }

    /**
     * Create an instance of {@link NssOffenderHeight }
     * 
     */
    public NssOffenderHeight createNssOffenderHeight() {
        return new NssOffenderHeight();
    }

    /**
     * Create an instance of {@link NssOffenderAddress }
     * 
     */
    public NssOffenderAddress createNssOffenderAddress() {
        return new NssOffenderAddress();
    }

    /**
     * Create an instance of {@link NSSProductMapHolder }
     * 
     */
    public NSSProductMapHolder createNSSProductMapHolder() {
        return new NSSProductMapHolder();
    }

    /**
     * Create an instance of {@link NssRecordKey }
     * 
     */
    public NssRecordKey createNssRecordKey() {
        return new NssRecordKey();
    }

   
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NSSMapHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BGC")
    public JAXBElement<NSSMapHolder> createBGC(NSSMapHolder value) {
        return new JAXBElement<NSSMapHolder>(_BGC_QNAME, NSSMapHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "secureKey")
    public JAXBElement<Integer> createSecureKey(Integer value) {
        return new JAXBElement<Integer>(_SecureKey_QNAME, Integer.class, null, value);
    }

}
