//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.11 at 01:16:40 PM IST 
//


package springapp.domain.NSS.NssDetailResponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NssDetailOffenders complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NssDetailOffenders">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offender" type="{}NssDetailOffender" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NssDetailOffenders", propOrder = {
    "offender"
})
public class NssDetailOffenders {

    protected List<NssDetailOffender> offender;
    
    @XmlAttribute(name = "qtyFound")
    protected String qtyFound;
    @XmlAttribute(name = "qtyReturned")
    protected String qtyReturned;

    /**
     * Gets the value of the offender property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offender property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffender().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NssDetailOffender }
     * 
     * 
     */
    public List<NssDetailOffender> getOffender() {
        if (offender == null) {
            offender = new ArrayList<NssDetailOffender>();
        }
        return this.offender;
    }
    

    /**
     * Gets the value of the qtyFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyFound() {
        return qtyFound;
    }

    /**
     * Sets the value of the qtyFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyFound(String value) {
        this.qtyFound = value;
    }

    /**
     * Gets the value of the qtyReturned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyReturned() {
        return qtyReturned;
    }

    /**
     * Sets the value of the qtyReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyReturned(String value) {
        this.qtyReturned = value;
    }


}
