//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.11 at 01:16:40 PM IST 
//


package springapp.domain.NSS.NssDetailResponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NssDetailOffence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NssDetailOffence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="disposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="degreeOfOffense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sentence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="probation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="confinement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrestingAgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originatingAgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jurisdiction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="plea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="courtDecision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="courtCosts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="offenseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sentenceDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dispositionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fileDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recordDetails" type="{}NssRecordDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NssDetailOffence", propOrder = {
    "description",
    "disposition",
    "degreeOfOffense",
    "sentence",
    "probation",
    "confinement",
    "arrestingAgency",
    "originatingAgency",
    "jurisdiction",
    "statute",
    "plea",
    "courtDecision",
    "courtCosts",
    "fine",
    "offenseDate",
    "arrestDate",
    "sentenceDate",
    "dispositionDate",
    "fileDate",
    "recordDetails"
})
public class NssDetailOffence {

    protected String description;
    protected String disposition;
    protected String degreeOfOffense;
    protected String sentence;
    protected String probation;
    protected String confinement;
    protected String arrestingAgency;
    protected String originatingAgency;
    protected String jurisdiction;
    protected String statute;
    protected String plea;
    protected String courtDecision;
    protected String courtCosts;
    protected String fine;
    protected String offenseDate;
    protected String arrestDate;
    protected String sentenceDate;
    protected String dispositionDate;
    protected String fileDate;
    protected List<NssRecordDetails> recordDetails;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the disposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisposition() {
        return disposition;
    }

    /**
     * Sets the value of the disposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisposition(String value) {
        this.disposition = value;
    }

    /**
     * Gets the value of the degreeOfOffense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeOfOffense() {
        return degreeOfOffense;
    }

    /**
     * Sets the value of the degreeOfOffense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeOfOffense(String value) {
        this.degreeOfOffense = value;
    }

    /**
     * Gets the value of the sentence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentence() {
        return sentence;
    }

    /**
     * Sets the value of the sentence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentence(String value) {
        this.sentence = value;
    }

    /**
     * Gets the value of the probation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProbation() {
        return probation;
    }

    /**
     * Sets the value of the probation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProbation(String value) {
        this.probation = value;
    }

    /**
     * Gets the value of the confinement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfinement() {
        return confinement;
    }

    /**
     * Sets the value of the confinement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfinement(String value) {
        this.confinement = value;
    }

    /**
     * Gets the value of the arrestingAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrestingAgency() {
        return arrestingAgency;
    }

    /**
     * Sets the value of the arrestingAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrestingAgency(String value) {
        this.arrestingAgency = value;
    }

    /**
     * Gets the value of the originatingAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingAgency() {
        return originatingAgency;
    }

    /**
     * Sets the value of the originatingAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingAgency(String value) {
        this.originatingAgency = value;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurisdiction() {
        return jurisdiction;
    }

    /**
     * Sets the value of the jurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurisdiction(String value) {
        this.jurisdiction = value;
    }

    /**
     * Gets the value of the statute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatute() {
        return statute;
    }

    /**
     * Sets the value of the statute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatute(String value) {
        this.statute = value;
    }

    /**
     * Gets the value of the plea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlea() {
        return plea;
    }

    /**
     * Sets the value of the plea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlea(String value) {
        this.plea = value;
    }

    /**
     * Gets the value of the courtDecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourtDecision() {
        return courtDecision;
    }

    /**
     * Sets the value of the courtDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtDecision(String value) {
        this.courtDecision = value;
    }

    /**
     * Gets the value of the courtCosts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourtCosts() {
        return courtCosts;
    }

    /**
     * Sets the value of the courtCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtCosts(String value) {
        this.courtCosts = value;
    }

    /**
     * Gets the value of the fine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFine() {
        return fine;
    }

    /**
     * Sets the value of the fine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFine(String value) {
        this.fine = value;
    }

    /**
     * Gets the value of the offenseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenseDate() {
        return offenseDate;
    }

    /**
     * Sets the value of the offenseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenseDate(String value) {
        this.offenseDate = value;
    }

    /**
     * Gets the value of the arrestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrestDate() {
        return arrestDate;
    }

    /**
     * Sets the value of the arrestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrestDate(String value) {
        this.arrestDate = value;
    }

    /**
     * Gets the value of the sentenceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentenceDate() {
        return sentenceDate;
    }

    /**
     * Sets the value of the sentenceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentenceDate(String value) {
        this.sentenceDate = value;
    }

    /**
     * Gets the value of the dispositionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispositionDate() {
        return dispositionDate;
    }

    /**
     * Sets the value of the dispositionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispositionDate(String value) {
        this.dispositionDate = value;
    }

    /**
     * Gets the value of the fileDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDate() {
        return fileDate;
    }

    /**
     * Sets the value of the fileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDate(String value) {
        this.fileDate = value;
    }

    /**
     * Gets the value of the recordDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NssRecordDetails }
     * 
     * 
     */
    public List<NssRecordDetails> getRecordDetails() {
        if (recordDetails == null) {
            recordDetails = new ArrayList<NssRecordDetails>();
        }
        return this.recordDetails;
    }

}
