//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b31 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.11 at 01:16:40 PM IST 
//


package springapp.domain.NSS.NssDetailResponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the NssDetailResponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BGC_QNAME = new QName("", "BGC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: NssDetailResponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NssOffMapHolder }
     * 
     */
    public NssOffMapHolder createNssOffMapHolder() {
        return new NssOffMapHolder();
    }

    /**
     * Create an instance of {@link NssDetailOffenders }
     * 
     */
    public NssDetailOffenders createNssDetailOffenders() {
        return new NssDetailOffenders();
    }

    /**
     * Create an instance of {@link NssOffResponse }
     * 
     */
    public NssOffResponse createNssOffResponse() {
        return new NssOffResponse();
    }

    /**
     * Create an instance of {@link NssDetailOffences }
     * 
     */
    public NssDetailOffences createNssDetailOffences() {
        return new NssDetailOffences();
    }

    /**
     * Create an instance of {@link NssDetailOffence }
     * 
     */
    public NssDetailOffence createNssDetailOffence() {
        return new NssDetailOffence();
    }

    /**
     * Create an instance of {@link NssRecordSupplements }
     * 
     */
    public NssRecordSupplements createNssRecordSupplements() {
        return new NssRecordSupplements();
    }

    /**
     * Create an instance of {@link NssOffProductHolder }
     * 
     */
    public NssOffProductHolder createNssOffProductHolder() {
        return new NssOffProductHolder();
    }

    /**
     * Create an instance of {@link NssDetail }
     * 
     */
    public NssDetail createNssDetail() {
        return new NssDetail();
    }

    /**
     * Create an instance of {@link NssUSOneSearchKey }
     * 
     */
    public NssUSOneSearchKey createNssUSOneSearchKey() {
        return new NssUSOneSearchKey();
    }

    /**
     * Create an instance of {@link NssDetailOffender }
     * 
     */
    public NssDetailOffender createNssDetailOffender() {
        return new NssDetailOffender();
    }

    /**
     * Create an instance of {@link NssRecordDetail }
     * 
     */
    public NssRecordDetail createNssRecordDetail() {
        return new NssRecordDetail();
    }

    /**
     * Create an instance of {@link NssRecordDetails }
     * 
     */
    public NssRecordDetails createNssRecordDetails() {
        return new NssRecordDetails();
    }

    /**
     * Create an instance of {@link NssRecordDetailSupplement }
     * 
     */
    public NssRecordDetailSupplement createNssRecordDetailSupplement() {
        return new NssRecordDetailSupplement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NssOffMapHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BGC")
    public JAXBElement<NssOffMapHolder> createBGC(NssOffMapHolder value) {
        return new JAXBElement<NssOffMapHolder>(_BGC_QNAME, NssOffMapHolder.class, null, value);
    }

}
